// ════════════════════════════════════════════
// VOCABULARY DATA — DE / EN / ES / IT
// Phase 1 of the expansion toward 1000 words/level.
// Structure: window.VOCAB = { beginner:[...], intermediate:[...], expert:[...] }
// Each entry: {de, en, es, it}
// To add more words later, just append more objects to the arrays below —
// no other code needs to change.
// ════════════════════════════════════════════
window.VOCAB = {

beginner:[
  // --- original core set ---
  {de:"Hund",en:"dog",es:"perro",it:"cane"},{de:"Katze",en:"cat",es:"gato",it:"gatto"},
  {de:"Haus",en:"house",es:"casa",it:"casa"},{de:"Wasser",en:"water",es:"agua",it:"acqua"},
  {de:"Brot",en:"bread",es:"pan",it:"pane"},{de:"rot",en:"red",es:"rojo",it:"rosso"},
  {de:"blau",en:"blue",es:"azul",it:"blu"},{de:"Mutter",en:"mother",es:"madre",it:"madre"},
  {de:"Vater",en:"father",es:"padre",it:"padre"},{de:"Buch",en:"book",es:"libro",it:"libro"},
  {de:"Tisch",en:"table",es:"mesa",it:"tavolo"},{de:"Stuhl",en:"chair",es:"silla",it:"sedia"},
  {de:"Fenster",en:"window",es:"ventana",it:"finestra"},{de:"Tür",en:"door",es:"puerta",it:"porta"},
  {de:"Auto",en:"car",es:"coche",it:"macchina"},{de:"Baum",en:"tree",es:"árbol",it:"albero"},
  {de:"Sonne",en:"sun",es:"sol",it:"sole"},{de:"Mond",en:"moon",es:"luna",it:"luna"},
  {de:"Apfel",en:"apple",es:"manzana",it:"mela"},{de:"Kind",en:"child",es:"niño",it:"bambino"},
  {de:"Schule",en:"school",es:"escuela",it:"scuola"},{de:"Stadt",en:"city",es:"ciudad",it:"città"},
  {de:"grün",en:"green",es:"verde",it:"verde"},{de:"Milch",en:"milk",es:"leche",it:"latte"},
  {de:"Bett",en:"bed",es:"cama",it:"letto"},{de:"Vogel",en:"bird",es:"pájaro",it:"uccello"},
  {de:"Fisch",en:"fish",es:"pez",it:"pesce"},{de:"Blume",en:"flower",es:"flor",it:"fiore"},
  {de:"Hand",en:"hand",es:"mano",it:"mano"},{de:"Auge",en:"eye",es:"ojo",it:"occhio"},
  {de:"Nase",en:"nose",es:"nariz",it:"naso"},{de:"Ohr",en:"ear",es:"oreja",it:"orecchio"},
  {de:"Mund",en:"mouth",es:"boca",it:"bocca"},{de:"Kopf",en:"head",es:"cabeza",it:"testa"},
  {de:"Fuß",en:"foot",es:"pie",it:"piede"},{de:"Arm",en:"arm",es:"brazo",it:"braccio"},
  {de:"Bein",en:"leg",es:"pierna",it:"gamba"},{de:"Herz",en:"heart",es:"corazón",it:"cuore"},
  {de:"Hals",en:"neck",es:"cuello",it:"collo"},{de:"Rücken",en:"back",es:"espalda",it:"schiena"},
  {de:"Finger",en:"finger",es:"dedo",it:"dito"},{de:"eins",en:"one",es:"uno",it:"uno"},
  {de:"zwei",en:"two",es:"dos",it:"due"},{de:"drei",en:"three",es:"tres",it:"tre"},
  {de:"vier",en:"four",es:"cuatro",it:"quattro"},{de:"fünf",en:"five",es:"cinco",it:"cinque"},
  {de:"sechs",en:"six",es:"seis",it:"sei"},{de:"sieben",en:"seven",es:"siete",it:"sette"},
  {de:"acht",en:"eight",es:"ocho",it:"otto"},{de:"neun",en:"nine",es:"nueve",it:"nove"},
  {de:"zehn",en:"ten",es:"diez",it:"dieci"},{de:"Montag",en:"Monday",es:"lunes",it:"lunedì"},
  {de:"Dienstag",en:"Tuesday",es:"martes",it:"martedì"},{de:"Mittwoch",en:"Wednesday",es:"miércoles",it:"mercoledì"},
  {de:"Donnerstag",en:"Thursday",es:"jueves",it:"giovedì"},{de:"Freitag",en:"Friday",es:"viernes",it:"venerdì"},
  {de:"Samstag",en:"Saturday",es:"sábado",it:"sabato"},{de:"Sonntag",en:"Sunday",es:"domingo",it:"domenica"},
  {de:"Januar",en:"January",es:"enero",it:"gennaio"},{de:"Februar",en:"February",es:"febrero",it:"febbraio"},
  {de:"März",en:"March",es:"marzo",it:"marzo"},{de:"April",en:"April",es:"abril",it:"aprile"},
  {de:"Mai",en:"May",es:"mayo",it:"maggio"},{de:"Juni",en:"June",es:"junio",it:"giugno"},
  {de:"Juli",en:"July",es:"julio",it:"luglio"},{de:"August",en:"August",es:"agosto",it:"agosto"},
  {de:"September",en:"September",es:"septiembre",it:"settembre"},{de:"Oktober",en:"October",es:"octubre",it:"ottobre"},
  {de:"November",en:"November",es:"noviembre",it:"novembre"},{de:"Dezember",en:"December",es:"diciembre",it:"dicembre"},
  {de:"Küche",en:"kitchen",es:"cocina",it:"cucina"},{de:"Badezimmer",en:"bathroom",es:"baño",it:"bagno"},
  {de:"Schlafzimmer",en:"bedroom",es:"dormitorio",it:"camera da letto"},{de:"Garten",en:"garden",es:"jardín",it:"giardino"},
  {de:"Straße",en:"street",es:"calle",it:"strada"},{de:"Markt",en:"market",es:"mercado",it:"mercato"},
  {de:"Supermarkt",en:"supermarket",es:"supermercado",it:"supermercato"},{de:"Bäckerei",en:"bakery",es:"panadería",it:"panetteria"},
  {de:"Restaurant",en:"restaurant",es:"restaurante",it:"ristorante"},{de:"Café",en:"café",es:"café",it:"bar"},
  {de:"Apotheke",en:"pharmacy",es:"farmacia",it:"farmacia"},{de:"Bank",en:"bank",es:"banco",it:"banca"},
  {de:"Bibliothek",en:"library",es:"biblioteca",it:"biblioteca"},{de:"Flughafen",en:"airport",es:"aeropuerto",it:"aeroporto"},
  {de:"Bahnhof",en:"train station",es:"estación",it:"stazione"},{de:"Zug",en:"train",es:"tren",it:"treno"},
  {de:"Bus",en:"bus",es:"autobús",it:"autobus"},{de:"Flugzeug",en:"airplane",es:"avión",it:"aereo"},
  {de:"Schiff",en:"ship",es:"barco",it:"nave"},{de:"Fahrrad",en:"bicycle",es:"bicicleta",it:"bicicletta"},
  {de:"Telefon",en:"telephone",es:"teléfono",it:"telefono"},{de:"Computer",en:"computer",es:"ordenador",it:"computer"},
  {de:"Schlüssel",en:"key",es:"llave",it:"chiave"},{de:"Brille",en:"glasses",es:"gafas",it:"occhiali"},
  {de:"Uhr",en:"clock",es:"reloj",it:"orologio"},{de:"Tasche",en:"bag",es:"bolso",it:"borsa"},
  {de:"Schuhe",en:"shoes",es:"zapatos",it:"scarpe"},{de:"Hemd",en:"shirt",es:"camisa",it:"camicia"},
  {de:"Hose",en:"trousers",es:"pantalón",it:"pantaloni"},{de:"Jacke",en:"jacket",es:"chaqueta",it:"giacca"},

  // --- new: numbers 11-1000 ---
  {de:"elf",en:"eleven",es:"once",it:"undici"},{de:"zwölf",en:"twelve",es:"doce",it:"dodici"},
  {de:"dreizehn",en:"thirteen",es:"trece",it:"tredici"},{de:"vierzehn",en:"fourteen",es:"catorce",it:"quattordici"},
  {de:"fünfzehn",en:"fifteen",es:"quince",it:"quindici"},{de:"sechzehn",en:"sixteen",es:"dieciséis",it:"sedici"},
  {de:"siebzehn",en:"seventeen",es:"diecisiete",it:"diciassette"},{de:"achtzehn",en:"eighteen",es:"dieciocho",it:"diciotto"},
  {de:"neunzehn",en:"nineteen",es:"diecinueve",it:"diciannove"},{de:"zwanzig",en:"twenty",es:"veinte",it:"venti"},
  {de:"dreißig",en:"thirty",es:"treinta",it:"trenta"},{de:"vierzig",en:"forty",es:"cuarenta",it:"quaranta"},
  {de:"fünfzig",en:"fifty",es:"cincuenta",it:"cinquanta"},{de:"hundert",en:"hundred",es:"cien",it:"cento"},
  {de:"tausend",en:"thousand",es:"mil",it:"mille"},

  // --- new: time ---
  {de:"heute",en:"today",es:"hoy",it:"oggi"},{de:"morgen",en:"tomorrow",es:"mañana",it:"domani"},
  {de:"gestern",en:"yesterday",es:"ayer",it:"ieri"},{de:"jetzt",en:"now",es:"ahora",it:"adesso"},
  {de:"später",en:"later",es:"más tarde",it:"più tardi"},{de:"früh",en:"early",es:"temprano",it:"presto"},
  {de:"spät",en:"late",es:"tarde",it:"tardi"},{de:"Woche",en:"week",es:"semana",it:"settimana"},
  {de:"Monat",en:"month",es:"mes",it:"mese"},{de:"Jahr",en:"year",es:"año",it:"anno"},
  {de:"Stunde",en:"hour",es:"hora",it:"ora"},{de:"Minute",en:"minute",es:"minuto",it:"minuto"},
  {de:"Vormittag",en:"morning",es:"mañana",it:"mattina"},{de:"Nachmittag",en:"afternoon",es:"tarde",it:"pomeriggio"},
  {de:"Abend",en:"evening",es:"noche",it:"sera"},{de:"Nacht",en:"night",es:"noche",it:"notte"},

  // --- new: weather & seasons ---
  {de:"Wetter",en:"weather",es:"tiempo",it:"tempo"},{de:"Regen",en:"rain",es:"lluvia",it:"pioggia"},
  {de:"Schnee",en:"snow",es:"nieve",it:"neve"},{de:"Wind",en:"wind",es:"viento",it:"vento"},
  {de:"Wolke",en:"cloud",es:"nube",it:"nuvola"},{de:"Nebel",en:"fog",es:"niebla",it:"nebbia"},
  {de:"Gewitter",en:"thunderstorm",es:"tormenta",it:"temporale"},{de:"kalt",en:"cold",es:"frío",it:"freddo"},
  {de:"warm",en:"warm",es:"cálido",it:"caldo"},{de:"heiß",en:"hot",es:"caliente",it:"molto caldo"},
  {de:"Frühling",en:"spring",es:"primavera",it:"primavera"},{de:"Sommer",en:"summer",es:"verano",it:"estate"},
  {de:"Herbst",en:"autumn",es:"otoño",it:"autunno"},{de:"Winter",en:"winter",es:"invierno",it:"inverno"},

  // --- new: animals ---
  {de:"Tier",en:"animal",es:"animal",it:"animale"},{de:"Pferd",en:"horse",es:"caballo",it:"cavallo"},
  {de:"Kuh",en:"cow",es:"vaca",it:"mucca"},{de:"Schwein",en:"pig",es:"cerdo",it:"maiale"},
  {de:"Schaf",en:"sheep",es:"oveja",it:"pecora"},{de:"Huhn",en:"chicken",es:"pollo",it:"pollo"},
  {de:"Ente",en:"duck",es:"pato",it:"anatra"},{de:"Maus",en:"mouse",es:"ratón",it:"topo"},
  {de:"Löwe",en:"lion",es:"león",it:"leone"},{de:"Elefant",en:"elephant",es:"elefante",it:"elefante"},
  {de:"Affe",en:"monkey",es:"mono",it:"scimmia"},{de:"Bär",en:"bear",es:"oso",it:"orso"},

  // --- new: colors ---
  {de:"gelb",en:"yellow",es:"amarillo",it:"giallo"},{de:"schwarz",en:"black",es:"negro",it:"nero"},
  {de:"weiß",en:"white",es:"blanco",it:"bianco"},{de:"orange",en:"orange",es:"naranja",it:"arancione"},
  {de:"braun",en:"brown",es:"marrón",it:"marrone"},{de:"grau",en:"grey",es:"gris",it:"grigio"},
  {de:"rosa",en:"pink",es:"rosa",it:"rosa"},{de:"lila",en:"purple",es:"morado",it:"viola"},

  // --- new: common adjectives ---
  {de:"groß",en:"big",es:"grande",it:"grande"},{de:"klein",en:"small",es:"pequeño",it:"piccolo"},
  {de:"schnell",en:"fast",es:"rápido",it:"veloce"},{de:"langsam",en:"slow",es:"lento",it:"lento"},
  {de:"neu",en:"new",es:"nuevo",it:"nuovo"},{de:"alt",en:"old",es:"viejo",it:"vecchio"},
  {de:"gut",en:"good",es:"bueno",it:"buono"},{de:"schlecht",en:"bad",es:"malo",it:"cattivo"},
  {de:"schön",en:"beautiful",es:"hermoso",it:"bello"},{de:"hässlich",en:"ugly",es:"feo",it:"brutto"},
  {de:"glücklich",en:"happy",es:"feliz",it:"felice"},{de:"traurig",en:"sad",es:"triste",it:"triste"},
  {de:"müde",en:"tired",es:"cansado",it:"stanco"},{de:"hungrig",en:"hungry",es:"hambriento",it:"affamato"},
  {de:"durstig",en:"thirsty",es:"sediento",it:"assetato"},

  // --- new: common verbs ---
  {de:"essen",en:"to eat",es:"comer",it:"mangiare"},{de:"trinken",en:"to drink",es:"beber",it:"bere"},
  {de:"schlafen",en:"to sleep",es:"dormir",it:"dormire"},{de:"gehen",en:"to go",es:"ir",it:"andare"},
  {de:"kommen",en:"to come",es:"venir",it:"venire"},{de:"sehen",en:"to see",es:"ver",it:"vedere"},
  {de:"hören",en:"to hear",es:"oír",it:"sentire"},{de:"sprechen",en:"to speak",es:"hablar",it:"parlare"},
  {de:"lesen",en:"to read",es:"leer",it:"leggere"},{de:"schreiben",en:"to write",es:"escribir",it:"scrivere"},
  {de:"kaufen",en:"to buy",es:"comprar",it:"comprare"},{de:"verkaufen",en:"to sell",es:"vender",it:"vendere"},
  {de:"spielen",en:"to play",es:"jugar",it:"giocare"},{de:"arbeiten",en:"to work",es:"trabajar",it:"lavorare"},
  {de:"lernen",en:"to learn",es:"aprender",it:"imparare"},{de:"lieben",en:"to love",es:"amar",it:"amare"},
  {de:"mögen",en:"to like",es:"gustar",it:"piacere"},{de:"kochen",en:"to cook",es:"cocinar",it:"cucinare"},
  {de:"öffnen",en:"to open",es:"abrir",it:"aprire"},{de:"schließen",en:"to close",es:"cerrar",it:"chiudere"},
  {de:"beginnen",en:"to begin",es:"empezar",it:"iniziare"},{de:"enden",en:"to end",es:"terminar",it:"finire"},
  {de:"warten",en:"to wait",es:"esperar",it:"aspettare"},{de:"helfen",en:"to help",es:"ayudar",it:"aiutare"},
  {de:"verstehen",en:"to understand",es:"entender",it:"capire"},{de:"denken",en:"to think",es:"pensar",it:"pensare"},
  {de:"wissen",en:"to know",es:"saber",it:"sapere"},

  // --- new: house extra ---
  {de:"Wohnzimmer",en:"living room",es:"salón",it:"soggiorno"},{de:"Balkon",en:"balcony",es:"balcón",it:"balcone"},
  {de:"Keller",en:"basement",es:"sótano",it:"cantina"},{de:"Dach",en:"roof",es:"techo",it:"tetto"},
  {de:"Wand",en:"wall",es:"pared",it:"parete"},{de:"Boden",en:"floor",es:"suelo",it:"pavimento"},
  {de:"Lampe",en:"lamp",es:"lámpara",it:"lampada"},{de:"Spiegel",en:"mirror",es:"espejo",it:"specchio"},
  {de:"Teppich",en:"carpet",es:"alfombra",it:"tappeto"},{de:"Kissen",en:"pillow",es:"almohada",it:"cuscino"},

  // --- new: family extra ---
  {de:"Bruder",en:"brother",es:"hermano",it:"fratello"},{de:"Schwester",en:"sister",es:"hermana",it:"sorella"},
  {de:"Großvater",en:"grandfather",es:"abuelo",it:"nonno"},{de:"Großmutter",en:"grandmother",es:"abuela",it:"nonna"},
  {de:"Onkel",en:"uncle",es:"tío",it:"zio"},{de:"Tante",en:"aunt",es:"tía",it:"zia"},
  {de:"Cousin",en:"cousin",es:"primo",it:"cugino"},{de:"Sohn",en:"son",es:"hijo",it:"figlio"},
  {de:"Tochter",en:"daughter",es:"hija",it:"figlia"},{de:"Ehemann",en:"husband",es:"marido",it:"marito"},
  {de:"Ehefrau",en:"wife",es:"esposa",it:"moglie"},{de:"Freund",en:"friend",es:"amigo",it:"amico"},
  {de:"Baby",en:"baby",es:"bebé",it:"bambino piccolo"},

  // --- new: food extra ---
  {de:"Fleisch",en:"meat",es:"carne",it:"carne"},{de:"Gemüse",en:"vegetables",es:"verduras",it:"verdura"},
  {de:"Obst",en:"fruit",es:"fruta",it:"frutta"},{de:"Reis",en:"rice",es:"arroz",it:"riso"},
  {de:"Nudeln",en:"pasta",es:"pasta",it:"pasta"},{de:"Ei",en:"egg",es:"huevo",it:"uovo"},
  {de:"Käse",en:"cheese",es:"queso",it:"formaggio"},{de:"Zucker",en:"sugar",es:"azúcar",it:"zucchero"},
  {de:"Salz",en:"salt",es:"sal",it:"sale"},{de:"Kaffee",en:"coffee",es:"café",it:"caffè"},
  {de:"Tee",en:"tea",es:"té",it:"tè"},{de:"Bier",en:"beer",es:"cerveza",it:"birra"},
  {de:"Wein",en:"wine",es:"vino",it:"vino"},{de:"Suppe",en:"soup",es:"sopa",it:"zuppa"},
  {de:"Kuchen",en:"cake",es:"pastel",it:"torta"},{de:"Schokolade",en:"chocolate",es:"chocolate",it:"cioccolato"},

  // --- new: transport extra ---
  {de:"U-Bahn",en:"subway",es:"metro",it:"metropolitana"},{de:"Taxi",en:"taxi",es:"taxi",it:"taxi"},
  {de:"Motorrad",en:"motorcycle",es:"motocicleta",it:"motocicletta"},{de:"Straßenbahn",en:"tram",es:"tranvía",it:"tram"},
],

intermediate:[
  // --- original core set ---
  {de:"Freiheit",en:"freedom",es:"libertad",it:"libertà"},{de:"Gerechtigkeit",en:"justice",es:"justicia",it:"giustizia"},
  {de:"Regierung",en:"government",es:"gobierno",it:"governo"},{de:"Wissenschaft",en:"science",es:"ciencia",it:"scienza"},
  {de:"Gesellschaft",en:"society",es:"sociedad",it:"società"},{de:"Bildung",en:"education",es:"educación",it:"istruzione"},
  {de:"Umwelt",en:"environment",es:"medio ambiente",it:"ambiente"},{de:"Wirtschaft",en:"economy",es:"economía",it:"economia"},
  {de:"Reise",en:"journey",es:"viaje",it:"viaggio"},{de:"Erfahrung",en:"experience",es:"experiencia",it:"esperienza"},
  {de:"Entwicklung",en:"development",es:"desarrollo",it:"sviluppo"},{de:"Verantwortung",en:"responsibility",es:"responsabilidad",it:"responsabilità"},
  {de:"Entscheidung",en:"decision",es:"decisión",it:"decisione"},{de:"Beziehung",en:"relationship",es:"relación",it:"relazione"},
  {de:"Vertrauen",en:"trust",es:"confianza",it:"fiducia"},{de:"Kenntnis",en:"knowledge",es:"conocimiento",it:"conoscenza"},
  {de:"Fähigkeit",en:"ability",es:"habilidad",it:"abilità"},{de:"Erfolg",en:"success",es:"éxito",it:"successo"},
  {de:"Niederlage",en:"defeat",es:"derrota",it:"sconfitta"},{de:"Wahrnehmung",en:"perception",es:"percepción",it:"percezione"},
  {de:"Fortschritt",en:"progress",es:"progreso",it:"progresso"},{de:"Nachhaltigkeit",en:"sustainability",es:"sostenibilidad",it:"sostenibilità"},
  {de:"Bewusstsein",en:"awareness",es:"conciencia",it:"consapevolezza"},{de:"Herausforderung",en:"challenge",es:"desafío",it:"sfida"},
  {de:"Gleichgewicht",en:"balance",es:"equilibrio",it:"equilibrio"},{de:"Einfluss",en:"influence",es:"influencia",it:"influenza"},
  {de:"Verpflichtung",en:"commitment",es:"compromiso",it:"impegno"},{de:"Widerstand",en:"resistance",es:"resistencia",it:"resistenza"},
  {de:"Vereinbarung",en:"agreement",es:"acuerdo",it:"accordo"},{de:"Meinungsverschiedenheit",en:"disagreement",es:"desacuerdo",it:"disaccordo"},
  {de:"Zusammenarbeit",en:"cooperation",es:"cooperación",it:"cooperazione"},{de:"Gemeinschaft",en:"community",es:"comunidad",it:"comunità"},
  {de:"Netzwerk",en:"network",es:"red",it:"rete"},{de:"Strategie",en:"strategy",es:"estrategia",it:"strategia"},
  {de:"Innovation",en:"innovation",es:"innovación",it:"innovazione"},{de:"Technologie",en:"technology",es:"tecnología",it:"tecnologia"},
  {de:"Forschung",en:"research",es:"investigación",it:"ricerca"},{de:"Analyse",en:"analysis",es:"análisis",it:"analisi"},
  {de:"Lösung",en:"solution",es:"solución",it:"soluzione"},{de:"Risiko",en:"risk",es:"riesgo",it:"rischio"},
  {de:"Chance",en:"opportunity",es:"oportunidad",it:"opportunità"},{de:"Wachstum",en:"growth",es:"crecimiento",it:"crescita"},
  {de:"Investition",en:"investment",es:"inversión",it:"investimento"},{de:"Steuer",en:"tax",es:"impuesto",it:"tassa"},
  {de:"Vertrag",en:"contract",es:"contrato",it:"contratto"},{de:"Gesetz",en:"law",es:"ley",it:"legge"},
  {de:"Recht",en:"right",es:"derecho",it:"diritto"},{de:"Pflicht",en:"duty",es:"deber",it:"dovere"},
  {de:"Bürger",en:"citizen",es:"ciudadano",it:"cittadino"},{de:"Demokratie",en:"democracy",es:"democracia",it:"democrazia"},
  {de:"Wahl",en:"election",es:"elección",it:"elezione"},{de:"Partei",en:"party",es:"partido",it:"partito"},
  {de:"Botschaft",en:"embassy",es:"embajada",it:"ambasciata"},{de:"Grenze",en:"border",es:"frontera",it:"confine"},
  {de:"Flüchtling",en:"refugee",es:"refugiado",it:"rifugiato"},{de:"Migration",en:"migration",es:"migración",it:"migrazione"},
  {de:"Integration",en:"integration",es:"integración",it:"integrazione"},{de:"Kultur",en:"culture",es:"cultura",it:"cultura"},
  {de:"Tradition",en:"tradition",es:"tradición",it:"tradizione"},{de:"Sprache",en:"language",es:"idioma",it:"lingua"},
  {de:"Geschichte",en:"history",es:"historia",it:"storia"},{de:"Kunst",en:"art",es:"arte",it:"arte"},
  {de:"Musik",en:"music",es:"música",it:"musica"},{de:"Theater",en:"theatre",es:"teatro",it:"teatro"},
  {de:"Roman",en:"novel",es:"novela",it:"romanzo"},{de:"Gedicht",en:"poem",es:"poema",it:"poesia"},
  {de:"Journalist",en:"journalist",es:"periodista",it:"giornalista"},{de:"Arzt",en:"doctor",es:"médico",it:"medico"},
  {de:"Anwalt",en:"lawyer",es:"abogado",it:"avvocato"},{de:"Ingenieur",en:"engineer",es:"ingeniero",it:"ingegnere"},
  {de:"Lehrer",en:"teacher",es:"profesor",it:"insegnante"},{de:"Forscher",en:"researcher",es:"investigador",it:"ricercatore"},
  {de:"Unternehmer",en:"entrepreneur",es:"empresario",it:"imprenditore"},{de:"Mitarbeiter",en:"employee",es:"empleado",it:"dipendente"},
  {de:"Kunde",en:"customer",es:"cliente",it:"cliente"},{de:"Konkurrent",en:"competitor",es:"competidor",it:"concorrente"},
  {de:"Umsatz",en:"revenue",es:"ingresos",it:"fatturato"},{de:"Gewinn",en:"profit",es:"beneficio",it:"profitto"},
  {de:"Verlust",en:"loss",es:"pérdida",it:"perdita"},{de:"Schulden",en:"debt",es:"deuda",it:"debito"},
  {de:"Kredit",en:"credit",es:"crédito",it:"credito"},{de:"Aktie",en:"share",es:"acción",it:"azione"},
  {de:"Versicherung",en:"insurance",es:"seguro",it:"assicurazione"},{de:"Gehalt",en:"salary",es:"salario",it:"stipendio"},
  {de:"Bewerbung",en:"application",es:"solicitud",it:"candidatura"},{de:"Kündigung",en:"dismissal",es:"despido",it:"licenziamento"},
  {de:"Urlaub",en:"vacation",es:"vacaciones",it:"vacanze"},{de:"Konferenz",en:"conference",es:"conferencia",it:"conferenza"},
  {de:"Präsentation",en:"presentation",es:"presentación",it:"presentazione"},{de:"Bericht",en:"report",es:"informe",it:"rapporto"},
  {de:"Projekt",en:"project",es:"proyecto",it:"progetto"},{de:"Frist",en:"deadline",es:"plazo",it:"scadenza"},
  {de:"Sitzung",en:"meeting",es:"reunión",it:"riunione"},{de:"Abteilung",en:"department",es:"departamento",it:"dipartimento"},
  {de:"Vorstand",en:"board",es:"consejo",it:"consiglio"},{de:"Geschäftsführer",en:"CEO",es:"director ejecutivo",it:"amministratore delegato"},
  {de:"Aktionär",en:"shareholder",es:"accionista",it:"azionista"},{de:"Fusion",en:"merger",es:"fusión",it:"fusione"},
  {de:"Konkurs",en:"bankruptcy",es:"quiebra",it:"fallimento"},{de:"Börse",en:"stock exchange",es:"bolsa",it:"borsa"},

  // --- new: technology ---
  {de:"Internet",en:"internet",es:"internet",it:"internet"},{de:"Software",en:"software",es:"software",it:"software"},
  {de:"Datei",en:"file",es:"archivo",it:"file"},{de:"Passwort",en:"password",es:"contraseña",it:"password"},
  {de:"Anwendung",en:"application",es:"aplicación",it:"applicazione"},{de:"Bildschirm",en:"screen",es:"pantalla",it:"schermo"},
  {de:"Tastatur",en:"keyboard",es:"teclado",it:"tastiera"},{de:"Verbindung",en:"connection",es:"conexión",it:"connessione"},
  {de:"herunterladen",en:"to download",es:"descargar",it:"scaricare"},{de:"hochladen",en:"to upload",es:"subir",it:"caricare"},

  // --- new: health ---
  {de:"Gesundheit",en:"health",es:"salud",it:"salute"},{de:"Krankheit",en:"illness",es:"enfermedad",it:"malattia"},
  {de:"Krankenhaus",en:"hospital",es:"hospital",it:"ospedale"},{de:"Medikament",en:"medicine",es:"medicamento",it:"medicina"},
  {de:"Impfung",en:"vaccination",es:"vacuna",it:"vaccinazione"},{de:"Ernährung",en:"nutrition",es:"alimentación",it:"alimentazione"},
  {de:"Bewegung",en:"exercise",es:"movimiento",it:"movimento"},{de:"Stress",en:"stress",es:"estrés",it:"stress"},
  {de:"Entspannung",en:"relaxation",es:"relajación",it:"rilassamento"},{de:"Schmerz",en:"pain",es:"dolor",it:"dolore"},

  // --- new: sport ---
  {de:"Sport",en:"sport",es:"deporte",it:"sport"},{de:"Mannschaft",en:"team",es:"equipo",it:"squadra"},
  {de:"Wettbewerb",en:"competition",es:"competición",it:"competizione"},{de:"Training",en:"training",es:"entrenamiento",it:"allenamento"},
  {de:"Sieg",en:"victory",es:"victoria",it:"vittoria"},{de:"Meisterschaft",en:"championship",es:"campeonato",it:"campionato"},
  {de:"Stadion",en:"stadium",es:"estadio",it:"stadio"},{de:"Schiedsrichter",en:"referee",es:"árbitro",it:"arbitro"},

  // --- new: environment ---
  {de:"Umweltverschmutzung",en:"pollution",es:"contaminación",it:"inquinamento"},
  {de:"erneuerbare Energie",en:"renewable energy",es:"energía renovable",it:"energia rinnovabile"},
  {de:"Recycling",en:"recycling",es:"reciclaje",it:"riciclaggio"},{de:"Emission",en:"emission",es:"emisión",it:"emissione"},
  {de:"Ressource",en:"resource",es:"recurso",it:"risorsa"},

  // --- new: education ---
  {de:"Ausbildung",en:"training",es:"formación",it:"formazione"},{de:"Universität",en:"university",es:"universidad",it:"università"},
  {de:"Prüfung",en:"exam",es:"examen",it:"esame"},{de:"Note",en:"grade",es:"nota",it:"voto"},
  {de:"Stipendium",en:"scholarship",es:"beca",it:"borsa di studio"},{de:"Abschluss",en:"degree",es:"título",it:"laurea"},

  // --- new: opinions & emotions ---
  {de:"Meinung",en:"opinion",es:"opinión",it:"opinione"},{de:"Überzeugung",en:"conviction",es:"convicción",it:"convinzione"},
  {de:"Vorurteil",en:"prejudice",es:"prejuicio",it:"pregiudizio"},{de:"Toleranz",en:"tolerance",es:"tolerancia",it:"tolleranza"},
  {de:"Respekt",en:"respect",es:"respeto",it:"rispetto"},{de:"Höflichkeit",en:"politeness",es:"cortesía",it:"cortesia"},
  {de:"Geduld",en:"patience",es:"paciencia",it:"pazienza"},{de:"Mut",en:"courage",es:"valentía",it:"coraggio"},
  {de:"Ehrlichkeit",en:"honesty",es:"honestidad",it:"onestà"},{de:"Neid",en:"envy",es:"envidia",it:"invidia"},
  {de:"Eifersucht",en:"jealousy",es:"celos",it:"gelosia"},{de:"Stolz",en:"pride",es:"orgullo",it:"orgoglio"},
  {de:"Scham",en:"shame",es:"vergüenza",it:"vergogna"},{de:"Angst",en:"fear",es:"miedo",it:"paura"},
  {de:"Hoffnung",en:"hope",es:"esperanza",it:"speranza"},{de:"Enttäuschung",en:"disappointment",es:"decepción",it:"delusione"},
  {de:"Erleichterung",en:"relief",es:"alivio",it:"sollievo"},

  // --- new: travel ---
  {de:"Unterkunft",en:"accommodation",es:"alojamiento",it:"alloggio"},{de:"Gepäck",en:"luggage",es:"equipaje",it:"bagaglio"},
  {de:"Reisepass",en:"passport",es:"pasaporte",it:"passaporto"},{de:"Visum",en:"visa",es:"visado",it:"visto"},
  {de:"Sehenswürdigkeit",en:"landmark",es:"atracción turística",it:"attrazione turistica"},
  {de:"Reiseführer",en:"travel guide",es:"guía turística",it:"guida turistica"},

  // --- new: cooking ---
  {de:"Rezept",en:"recipe",es:"receta",it:"ricetta"},{de:"Zutat",en:"ingredient",es:"ingrediente",it:"ingrediente"},
  {de:"braten",en:"to roast",es:"asar",it:"arrostire"},{de:"backen",en:"to bake",es:"hornear",it:"cuocere al forno"},
  {de:"schneiden",en:"to cut",es:"cortar",it:"tagliare"},

  // --- new: housing ---
  {de:"Vermieter",en:"landlord",es:"arrendador",it:"proprietario di casa"},{de:"Miete",en:"rent",es:"alquiler",it:"affitto"},
  {de:"Nebenkosten",en:"utility costs",es:"gastos adicionales",it:"spese accessorie"},{de:"Nachbar",en:"neighbor",es:"vecino",it:"vicino"},
  {de:"Umzug",en:"move",es:"mudanza",it:"trasloco"},

  // --- new: work ---
  {de:"Kollege",en:"colleague",es:"colega",it:"collega"},{de:"Chef",en:"boss",es:"jefe",it:"capo"},
  {de:"Teamarbeit",en:"teamwork",es:"trabajo en equipo",it:"lavoro di squadra"},{de:"Karriere",en:"career",es:"carrera",it:"carriera"},
  {de:"Beförderung",en:"promotion",es:"ascenso",it:"promozione"},{de:"Homeoffice",en:"home office",es:"teletrabajo",it:"lavoro da remoto"},
  {de:"Work-Life-Balance",en:"work-life balance",es:"equilibrio trabajo-vida",it:"equilibrio vita-lavoro"},

  // --- new: mind & habits ---
  {de:"Erinnerung",en:"memory",es:"recuerdo",it:"ricordo"},{de:"Traum",en:"dream",es:"sueño",it:"sogno"},
  {de:"Ziel",en:"goal",es:"meta",it:"obiettivo"},{de:"Plan",en:"plan",es:"plan",it:"piano"},
  {de:"Idee",en:"idea",es:"idea",it:"idea"},{de:"Vorschlag",en:"suggestion",es:"propuesta",it:"proposta"},
  {de:"Feedback",en:"feedback",es:"comentarios",it:"feedback"},{de:"Kritik",en:"criticism",es:"crítica",it:"critica"},
  {de:"Lob",en:"praise",es:"elogio",it:"elogio"},{de:"Gewohnheit",en:"habit",es:"hábito",it:"abitudine"},
  {de:"Routine",en:"routine",es:"rutina",it:"routine"},{de:"Veränderung",en:"change",es:"cambio",it:"cambiamento"},
  {de:"Anpassung",en:"adaptation",es:"adaptación",it:"adattamento"},{de:"Motivation",en:"motivation",es:"motivación",it:"motivazione"},
  {de:"Disziplin",en:"discipline",es:"disciplina",it:"disciplina"},{de:"Kreativität",en:"creativity",es:"creatividad",it:"creatività"},
  {de:"Konzentration",en:"concentration",es:"concentración",it:"concentrazione"},{de:"Selbstvertrauen",en:"self-confidence",es:"autoconfianza",it:"autostima"},
],

expert:[
  // --- original core set (academic) ---
  {de:"Epistemologie",en:"epistemology",es:"epistemología",it:"epistemologia"},{de:"Phänomenologie",en:"phenomenology",es:"fenomenología",it:"fenomenologia"},
  {de:"Ambiguität",en:"ambiguity",es:"ambigüedad",it:"ambiguità"},{de:"Paradigma",en:"paradigm",es:"paradigma",it:"paradigma"},
  {de:"Determinismus",en:"determinism",es:"determinismo",it:"determinismo"},{de:"Dialektik",en:"dialectic",es:"dialéctica",it:"dialettica"},
  {de:"Hegemonie",en:"hegemony",es:"hegemonía",it:"egemonia"},{de:"Metaphysik",en:"metaphysics",es:"metafísica",it:"metafisica"},
  {de:"Pluralismus",en:"pluralism",es:"pluralismo",it:"pluralismo"},{de:"Ästhetik",en:"aesthetics",es:"estética",it:"estetica"},
  {de:"Kausalität",en:"causality",es:"causalidad",it:"causalità"},{de:"Ontologie",en:"ontology",es:"ontología",it:"ontologia"},
  {de:"Utilitarismus",en:"utilitarianism",es:"utilitarismo",it:"utilitarismo"},{de:"Souveränität",en:"sovereignty",es:"soberanía",it:"sovranità"},
  {de:"Imperativ",en:"imperative",es:"imperativo",it:"imperativo"},{de:"Axiom",en:"axiom",es:"axioma",it:"assioma"},
  {de:"Kontingenz",en:"contingency",es:"contingencia",it:"contingenza"},{de:"Tautologie",en:"tautology",es:"tautología",it:"tautologia"},
  {de:"Divergenz",en:"divergence",es:"divergencia",it:"divergenza"},{de:"Resilienz",en:"resilience",es:"resiliencia",it:"resilienza"},
  {de:"Subsidiarität",en:"subsidiarity",es:"subsidiariedad",it:"sussidiarietà"},{de:"Syllogismus",en:"syllogism",es:"silogismo",it:"sillogismo"},
  {de:"Transzendenz",en:"transcendence",es:"trascendencia",it:"trascendenza"},{de:"Pragmatismus",en:"pragmatism",es:"pragmatismo",it:"pragmatismo"},
  {de:"Relativismus",en:"relativism",es:"relativismo",it:"relativismo"},{de:"Kognition",en:"cognition",es:"cognición",it:"cognizione"},
  {de:"Deduktion",en:"deduction",es:"deducción",it:"deduzione"},{de:"Induktion",en:"induction",es:"inducción",it:"induzione"},
  {de:"Postulat",en:"postulate",es:"postulado",it:"postulato"},{de:"Antithese",en:"antithesis",es:"antítesis",it:"antitesi"},
  {de:"Hypothese",en:"hypothesis",es:"hipótesis",it:"ipotesi"},{de:"Synthese",en:"synthesis",es:"síntesis",it:"sintesi"},
  {de:"Abstraktion",en:"abstraction",es:"abstracción",it:"astrazione"},{de:"Analogie",en:"analogy",es:"analogía",it:"analogia"},
  {de:"Paradoxon",en:"paradox",es:"paradoja",it:"paradosso"},{de:"Kohärenz",en:"coherence",es:"coherencia",it:"coerenza"},
  {de:"Konsistenz",en:"consistency",es:"consistencia",it:"consistenza"},{de:"Korrelation",en:"correlation",es:"correlación",it:"correlazione"},
  {de:"Konvergenz",en:"convergence",es:"convergencia",it:"convergenza"},{de:"Kontroverse",en:"controversy",es:"controversia",it:"controversia"},
  {de:"Konsens",en:"consensus",es:"consenso",it:"consenso"},{de:"Legitimität",en:"legitimacy",es:"legitimidad",it:"legittimità"},
  {de:"Autorität",en:"authority",es:"autoridad",it:"autorità"},{de:"Hierarchie",en:"hierarchy",es:"jerarquía",it:"gerarchia"},
  {de:"Bürokratie",en:"bureaucracy",es:"burocracia",it:"burocrazia"},{de:"Ideologie",en:"ideology",es:"ideología",it:"ideologia"},
  {de:"Utopie",en:"utopia",es:"utopía",it:"utopia"},{de:"Anarchie",en:"anarchy",es:"anarquía",it:"anarchia"},
  {de:"Totalitarismus",en:"totalitarianism",es:"totalitarismo",it:"totalitarismo"},{de:"Liberalismus",en:"liberalism",es:"liberalismo",it:"liberalismo"},
  {de:"Konservatismus",en:"conservatism",es:"conservadurismo",it:"conservatorismo"},{de:"Sozialismus",en:"socialism",es:"socialismo",it:"socialismo"},
  {de:"Kapitalismus",en:"capitalism",es:"capitalismo",it:"capitalismo"},{de:"Globalisierung",en:"globalization",es:"globalización",it:"globalizzazione"},
  {de:"Nationalismus",en:"nationalism",es:"nacionalismo",it:"nazionalismo"},{de:"Imperialismus",en:"imperialism",es:"imperialismo",it:"imperialismo"},
  {de:"Kolonialismus",en:"colonialism",es:"colonialismo",it:"colonialismo"},{de:"Diskriminierung",en:"discrimination",es:"discriminación",it:"discriminazione"},
  {de:"Emanzipation",en:"emancipation",es:"emancipación",it:"emancipazione"},{de:"Feminismus",en:"feminism",es:"feminismo",it:"femminismo"},
  {de:"Ökologie",en:"ecology",es:"ecología",it:"ecologia"},{de:"Biodiversität",en:"biodiversity",es:"biodiversidad",it:"biodiversità"},
  {de:"Klimawandel",en:"climate change",es:"cambio climático",it:"cambiamento climatico"},{de:"Quantenmechanik",en:"quantum mechanics",es:"mecánica cuántica",it:"meccanica quantistica"},
  {de:"Neurologie",en:"neurology",es:"neurología",it:"neurologia"},{de:"Psychoanalyse",en:"psychoanalysis",es:"psicoanálisis",it:"psicoanalisi"},
  {de:"Behaviourismus",en:"behaviourism",es:"conductismo",it:"comportamentismo"},{de:"Kognitionswissenschaft",en:"cognitive science",es:"ciencia cognitiva",it:"scienza cognitiva"},
  {de:"Linguistik",en:"linguistics",es:"lingüística",it:"linguistica"},{de:"Semiotik",en:"semiotics",es:"semiótica",it:"semiotica"},
  {de:"Hermeneutik",en:"hermeneutics",es:"hermenéutica",it:"ermeneutica"},{de:"Dekonstruktion",en:"deconstruction",es:"deconstrucción",it:"decostruzione"},
  {de:"Postmodernismus",en:"postmodernism",es:"posmodernismo",it:"postmodernismo"},{de:"Strukturalismus",en:"structuralism",es:"estructuralismo",it:"strutturalismo"},
  {de:"Existenzialismus",en:"existentialism",es:"existencialismo",it:"esistenzialismo"},{de:"Stoizismus",en:"stoicism",es:"estoicismo",it:"stoicismo"},
  {de:"Empirismus",en:"empiricism",es:"empirismo",it:"empirismo"},{de:"Rationalismus",en:"rationalism",es:"racionalismo",it:"razionalismo"},
  {de:"Skeptizismus",en:"scepticism",es:"escepticismo",it:"scetticismo"},{de:"Nihilismus",en:"nihilism",es:"nihilismo",it:"nichilismo"},
  {de:"Agnostizismus",en:"agnosticism",es:"agnosticismo",it:"agnosticismo"},{de:"Atheismus",en:"atheism",es:"ateísmo",it:"ateismo"},
  {de:"Theismus",en:"theism",es:"teísmo",it:"teismo"},{de:"Pantheismus",en:"pantheism",es:"panteísmo",it:"panteismo"},
  {de:"Mystizismus",en:"mysticism",es:"misticismo",it:"misticismo"},{de:"Eschatologie",en:"eschatology",es:"escatología",it:"escatologia"},
  {de:"Theodizee",en:"theodicy",es:"teodicea",it:"teodicea"},{de:"Phänomen",en:"phenomenon",es:"fenómeno",it:"fenomeno"},
  {de:"Dialektisch",en:"dialectical",es:"dialéctico",it:"dialettico"},{de:"Apriori",en:"a priori",es:"a priori",it:"a priori"},
  {de:"Aposteriori",en:"a posteriori",es:"a posteriori",it:"a posteriori"},{de:"Noumenon",en:"noumenon",es:"noúmeno",it:"noumeno"},
  {de:"Immanenz",en:"immanence",es:"inmanencia",it:"immanenza"},{de:"Dualismus",en:"dualism",es:"dualismo",it:"dualismo"},
  {de:"Monismus",en:"monism",es:"monismo",it:"monismo"},{de:"Reduktionismus",en:"reductionism",es:"reduccionismo",it:"riduzionismo"},
  {de:"Holismus",en:"holism",es:"holismo",it:"olismo"},{de:"Teleologie",en:"teleology",es:"teleología",it:"teleologia"},

  // --- new: general higher-level vocabulary (news, politics, economy, everyday professional life) ---
  {de:"Verhandlung",en:"negotiation",es:"negociación",it:"negoziazione"},{de:"Kompromiss",en:"compromise",es:"compromiso",it:"compromesso"},
  {de:"Effizienz",en:"efficiency",es:"eficiencia",it:"efficienza"},{de:"Transparenz",en:"transparency",es:"transparencia",it:"trasparenza"},
  {de:"Infrastruktur",en:"infrastructure",es:"infraestructura",it:"infrastruttura"},{de:"Digitalisierung",en:"digitalization",es:"digitalización",it:"digitalizzazione"},
  {de:"Automatisierung",en:"automation",es:"automatización",it:"automazione"},{de:"künstliche Intelligenz",en:"artificial intelligence",es:"inteligencia artificial",it:"intelligenza artificiale"},
  {de:"Algorithmus",en:"algorithm",es:"algoritmo",it:"algoritmo"},{de:"Datenschutz",en:"data protection",es:"protección de datos",it:"protezione dei dati"},
  {de:"Sicherheit",en:"security",es:"seguridad",it:"sicurezza"},{de:"Krise",en:"crisis",es:"crisis",it:"crisi"},
  {de:"Reform",en:"reform",es:"reforma",it:"riforma"},{de:"Subvention",en:"subsidy",es:"subvención",it:"sussidio"},
  {de:"Inflation",en:"inflation",es:"inflación",it:"inflazione"},{de:"Rezession",en:"recession",es:"recesión",it:"recessione"},
  {de:"Arbeitslosigkeit",en:"unemployment",es:"desempleo",it:"disoccupazione"},{de:"Mindestlohn",en:"minimum wage",es:"salario mínimo",it:"salario minimo"},
  {de:"Ungleichheit",en:"inequality",es:"desigualdad",it:"disuguaglianza"},{de:"Öffentlichkeit",en:"public opinion",es:"opinión pública",it:"opinione pubblica"},
  {de:"Zivilgesellschaft",en:"civil society",es:"sociedad civil",it:"società civile"},{de:"Menschenrechte",en:"human rights",es:"derechos humanos",it:"diritti umani"},
  {de:"Meinungsfreiheit",en:"freedom of speech",es:"libertad de expresión",it:"libertà di espressione"},{de:"Zensur",en:"censorship",es:"censura",it:"censura"},
  {de:"Korruption",en:"corruption",es:"corrupción",it:"corruzione"},{de:"Diplomatie",en:"diplomacy",es:"diplomacia",it:"diplomazia"},
  {de:"Verhältnismäßigkeit",en:"proportionality",es:"proporcionalidad",it:"proporzionalità"},{de:"Nachfrage",en:"demand",es:"demanda",it:"domanda"},
  {de:"Angebot",en:"supply",es:"oferta",it:"offerta"},{de:"Konjunktur",en:"economic cycle",es:"coyuntura económica",it:"congiuntura economica"},
  {de:"Haushalt",en:"budget",es:"presupuesto",it:"bilancio"},{de:"Prognose",en:"forecast",es:"pronóstico",it:"previsione"},
  {de:"Statistik",en:"statistics",es:"estadística",it:"statistica"},{de:"Umfrage",en:"survey",es:"encuesta",it:"sondaggio"},
  {de:"Mehrheit",en:"majority",es:"mayoría",it:"maggioranza"},{de:"Minderheit",en:"minority",es:"minoría",it:"minoranza"},
  {de:"Abstimmung",en:"vote",es:"votación",it:"votazione"},{de:"Koalition",en:"coalition",es:"coalición",it:"coalizione"},
  {de:"Opposition",en:"opposition",es:"oposición",it:"opposizione"},{de:"Verfassung",en:"constitution",es:"constitución",it:"costituzione"},
  {de:"Gericht",en:"court",es:"tribunal",it:"tribunale"},{de:"Urteil",en:"verdict",es:"sentencia",it:"sentenza"},
  {de:"Anklage",en:"indictment",es:"acusación",it:"accusa"},{de:"Verteidigung",en:"defense",es:"defensa",it:"difesa"},
  {de:"Berufung",en:"appeal",es:"apelación",it:"appello"},{de:"Vollstreckung",en:"enforcement",es:"ejecución",it:"esecuzione"},
  {de:"Verordnung",en:"regulation",es:"reglamento",it:"regolamento"},{de:"Vorschrift",en:"rule",es:"norma",it:"norma"},
  {de:"Zuständigkeit",en:"jurisdiction",es:"competencia",it:"competenza"},{de:"Delegation",en:"delegation",es:"delegación",it:"delegazione"},
  {de:"Ausschuss",en:"committee",es:"comité",it:"comitato"},{de:"Gremium",en:"panel",es:"panel",it:"organo"},
  {de:"Beschluss",en:"resolution",es:"resolución",it:"delibera"},{de:"Initiative",en:"initiative",es:"iniciativa",it:"iniziativa"},
  {de:"Reformbedarf",en:"need for reform",es:"necesidad de reforma",it:"necessità di riforma"},
  {de:"Wettbewerbsfähigkeit",en:"competitiveness",es:"competitividad",it:"competitività"},{de:"Produktivität",en:"productivity",es:"productividad",it:"produttività"},
  {de:"Innovationskraft",en:"innovative power",es:"capacidad de innovación",it:"capacità di innovazione"},
  {de:"Fachkräftemangel",en:"skilled labor shortage",es:"escasez de mano de obra cualificada",it:"carenza di manodopera qualificata"},
  {de:"digitale Kluft",en:"digital divide",es:"brecha digital",it:"divario digitale"},{de:"Cybersicherheit",en:"cybersecurity",es:"ciberseguridad",it:"cybersicurezza"},
  {de:"Datenverarbeitung",en:"data processing",es:"procesamiento de datos",it:"elaborazione dati"},
  {de:"Vernetzung",en:"interconnection",es:"interconexión",it:"interconnessione"},
  {de:"Automatisierungsgrad",en:"degree of automation",es:"grado de automatización",it:"grado di automazione"},
  {de:"Nachhaltigkeitsziel",en:"sustainability goal",es:"objetivo de sostenibilidad",it:"obiettivo di sostenibilità"},
  {de:"Lieferkette",en:"supply chain",es:"cadena de suministro",it:"catena di approvvigionamento"},
  {de:"Rohstoff",en:"raw material",es:"materia prima",it:"materia prima"},
  {de:"Handelsabkommen",en:"trade agreement",es:"acuerdo comercial",it:"accordo commerciale"},
  {de:"Zollpolitik",en:"tariff policy",es:"política arancelaria",it:"politica doganale"},
  {de:"Exportquote",en:"export quota",es:"cuota de exportación",it:"quota di esportazione"},
  {de:"Wechselkurs",en:"exchange rate",es:"tipo de cambio",it:"tasso di cambio"},
  {de:"Zentralbank",en:"central bank",es:"banco central",it:"banca centrale"},
  {de:"Geldpolitik",en:"monetary policy",es:"política monetaria",it:"politica monetaria"},
  {de:"Finanzmarkt",en:"financial market",es:"mercado financiero",it:"mercato finanziario"},
  {de:"Spekulation",en:"speculation",es:"especulación",it:"speculazione"},{de:"Volatilität",en:"volatility",es:"volatilidad",it:"volatilità"},
  {de:"Klimapolitik",en:"climate policy",es:"política climática",it:"politica climatica"},
  {de:"CO2-Ausstoß",en:"CO2 emissions",es:"emisiones de CO2",it:"emissioni di CO2"},
  {de:"Kreislaufwirtschaft",en:"circular economy",es:"economía circular",it:"economia circolare"},
  {de:"Naturschutz",en:"nature conservation",es:"conservación de la naturaleza",it:"tutela della natura"},
  {de:"Katastrophenschutz",en:"disaster prevention",es:"protección civil",it:"protezione civile"},
  {de:"Gesundheitssystem",en:"healthcare system",es:"sistema de salud",it:"sistema sanitario"},
  {de:"Pandemie",en:"pandemic",es:"pandemia",it:"pandemia"},{de:"Epidemie",en:"epidemic",es:"epidemia",it:"epidemia"},
  {de:"Impfpflicht",en:"vaccination mandate",es:"obligación de vacunación",it:"obbligo vaccinale"},
  {de:"Grundversorgung",en:"basic services",es:"suministro básico",it:"approvvigionamento di base"},
  {de:"Sozialstaat",en:"welfare state",es:"estado de bienestar",it:"stato sociale"},
  {de:"Altersvorsorge",en:"retirement provision",es:"previsión para la jubilación",it:"previdenza per la vecchiaia"},
  {de:"Rentensystem",en:"pension system",es:"sistema de pensiones",it:"sistema pensionistico"},
  {de:"Generationengerechtigkeit",en:"intergenerational fairness",es:"justicia intergeneracional",it:"giustizia intergenerazionale"},
  {de:"Bildungssystem",en:"education system",es:"sistema educativo",it:"sistema educativo"},
  {de:"Chancengleichheit",en:"equal opportunity",es:"igualdad de oportunidades",it:"pari opportunità"},
  {de:"Integrationspolitik",en:"integration policy",es:"política de integración",it:"politica di integrazione"},
  {de:"Sicherheitspolitik",en:"security policy",es:"política de seguridad",it:"politica di sicurezza"},
  {de:"Außenpolitik",en:"foreign policy",es:"política exterior",it:"politica estera"},
  {de:"Innenpolitik",en:"domestic policy",es:"política interior",it:"politica interna"},
  {de:"Gesetzgebung",en:"legislation",es:"legislación",it:"legislazione"},
  {de:"Rechtsstaat",en:"rule of law",es:"estado de derecho",it:"stato di diritto"},
  {de:"Grundrecht",en:"fundamental right",es:"derecho fundamental",it:"diritto fondamentale"},
  {de:"Machtverteilung",en:"distribution of power",es:"distribución del poder",it:"distribuzione del potere"},
]
};
